<?php
// Mtaita Tech - Database Installer
// Run this script once to set up the database and admin user

$step = $_GET['step'] ?? 'start';
$error = '';
$success = '';
$config_ok = false;

// Try to load existing .env
$env_path = __DIR__ . '/.env';
$env_example_path = __DIR__ . '/.env.example';

function loadEnvFile($path) {
    $vars = [];
    if (!file_exists($path)) return $vars;
    $lines = file($path, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
    foreach ($lines as $line) {
        $line = trim($line);
        if ($line === '' || str_starts_with($line, '#')) continue;
        $parts = explode('=', $line, 2);
        if (count($parts) !== 2) continue;
        $vars[trim($parts[0])] = trim($parts[1]);
    }
    return $vars;
}

function writeEnvFile($path, $vars) {
    $content = "# Mtaita Tech - Environment Configuration\n";
    $content .= "# Generated by install.php\n\n";
    $content .= "APP_ENV=production\n";
    $content .= "APP_DEBUG=false\n\n";
    $content .= "SITE_NAME=Mtaita Tech\n";
    $content .= "SITE_TAGLINE=IT & Graphic Design Agency\n";
    $content .= "SITE_URL=https://mtaitatech.online\n";
    $content .= "ADMIN_EMAIL={$vars['admin_email']}\n\n";
    $content .= "DB_HOST={$vars['db_host']}\n";
    $content .= "DB_NAME={$vars['db_name']}\n";
    $content .= "DB_USER={$vars['db_user']}\n";
    $content .= "DB_PASS={$vars['db_pass']}\n\n";
    $content .= "SMTP_HOST=smtp.gmail.com\n";
    $content .= "SMTP_PORT=587\n";
    $content .= "SMTP_USER=\n";
    $content .= "SMTP_PASS=\n";
    $content .= "FROM_EMAIL=\n";
    $content .= "FROM_NAME=Mtaita Tech\n";
    file_put_contents($path, $content);
}

$env_vars = loadEnvFile($env_path);

// Test DB connection
$test_host = $env_vars['DB_HOST'] ?? '';
$test_db   = $env_vars['DB_NAME'] ?? '';
$test_user = $env_vars['DB_USER'] ?? '';
$test_pass = $env_vars['DB_PASS'] ?? '';

if ($test_host && $test_db && $test_user) {
    try {
        $pdo_test = new PDO("mysql:host=$test_host;dbname=$test_db;charset=utf8mb4", $test_user, $test_pass, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        ]);
        $config_ok = true;
    } catch (PDOException $e) {
        $error = 'Database connection failed: ' . $e->getMessage();
    }
}

// Handle form submission
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action'])) {
    if ($_POST['action'] === 'save_env') {
        $vars = [
            'db_host' => trim($_POST['db_host']),
            'db_name' => trim($_POST['db_name']),
            'db_user' => trim($_POST['db_user']),
            'db_pass' => $_POST['db_pass'],
            'admin_email' => trim($_POST['admin_email']),
        ];
        try {
            writeEnvFile($env_path, $vars);
            $success = '.env file created.';
            $env_vars = loadEnvFile($env_path);
            $test_host = $vars['db_host'];
            $test_db   = $vars['db_name'];
            $test_user = $vars['db_user'];
            $test_pass = $vars['db_pass'];
            try {
                $pdo_test = new PDO("mysql:host=$test_host;dbname=$test_db;charset=utf8mb4", $test_user, $test_pass, [
                    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                ]);
                $config_ok = true;
                $success .= ' Database connection successful.';
            } catch (PDOException $e) {
                $error = 'Database connection failed: ' . $e->getMessage();
            }
        } catch (Exception $e) {
            $error = 'Could not write .env file.';
        }
    }

    if ($_POST['action'] === 'run_migrations' && $config_ok) {
        try {
            // Run all SQL files in order
            $sql_dir = __DIR__ . '/database';
            $sql_files = [
                'schema.sql',
                'migration_004_snippe.sql',
                'migration_005_lms_upgrade.sql',
                'migration_006_sms_notifications.sql',
                'migration_007_portfolio_categories.sql',
                'migration_008_sections.sql',
                'install_public_users.sql',
                'install_contacts.sql',
                'install_courses.sql',
                'install_enrollments.sql',
                'install_lessons.sql',
            ];

            $pdo_test->exec("SET FOREIGN_KEY_CHECKS = 0");

            foreach ($sql_files as $file) {
                $path = $sql_dir . '/' . $file;
                if (!file_exists($path)) continue;
                $sql = file_get_contents($path);
                if (trim($sql) === '') continue;
                // Split by semicolons for multi-statement execution
                $statements = explode(';', $sql);
                foreach ($statements as $stmt) {
                    $stmt = trim($stmt);
                    if ($stmt !== '') {
                        $pdo_test->exec($stmt);
                    }
                }
            }

            $pdo_test->exec("SET FOREIGN_KEY_CHECKS = 1");

            // Create default admin if not exists
            $check = $pdo_test->query("SELECT COUNT(*) FROM users")->fetchColumn();
            if ($check == 0) {
                $admin_password = password_hash('admin123', PASSWORD_DEFAULT);
                $pdo_test->exec("INSERT INTO users (username, password, role) VALUES ('admin', '$admin_password', 'admin')");
            }

            $success = 'Database setup complete! You can now <a href="admin/login">login to admin</a> with username <strong>admin</strong> and password <strong>admin123</strong>.';
        } catch (Exception $e) {
            $error = 'Migration failed: ' . $e->getMessage();
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Install — Mtaita Tech</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body { background: #f0f2f5; font-family: 'Segoe UI', sans-serif; }
        .install-wrap { max-width: 640px; margin: 60px auto; }
        .card { border: none; box-shadow: 0 2px 12px rgba(0,0,0,0.08); }
        .card-header { background: #0d6efd; color: #fff; font-weight: 700; }
        .brand { text-align: center; margin-bottom: 24px; }
        .brand img { height: 48px; }
        .brand h1 { font-size: 1.5rem; margin-top: 8px; }
    </style>
</head>
<body>
    <div class="install-wrap">
        <div class="brand">
            <img src="assets/img/jj.png" alt="Mtaita Tech">
            <h1>Mtaita Tech — Installation</h1>
        </div>

        <?php if ($error): ?>
            <div class="alert alert-danger"><?= htmlspecialchars($error) ?></div>
        <?php endif; ?>
        <?php if ($success): ?>
            <div class="alert alert-success"><?= $success ?></div>
        <?php endif; ?>

        <?php if ($config_ok): ?>
            <div class="card mb-4">
                <div class="card-header">Database Connected</div>
                <div class="card-body">
                    <p class="text-success">✓ Connected to <strong><?= htmlspecialchars($test_db) ?></strong> on <strong><?= htmlspecialchars($test_host) ?></strong></p>
                    <form method="POST">
                        <input type="hidden" name="action" value="run_migrations">
                        <p class="text-muted small">This will create all required tables and set up the default admin user.</p>
                        <button type="submit" class="btn btn-primary" onclick="return confirm('Run database migrations? Existing data will not be affected.');">
                            Run Database Setup
                        </button>
                    </form>
                </div>
            </div>
        <?php endif; ?>

        <div class="card">
            <div class="card-header">Database Configuration</div>
            <div class="card-body">
                <?php if (!file_exists($env_path)): ?>
                    <div class="alert alert-warning">No .env file found. Enter your database credentials below.</div>
                <?php elseif (!$config_ok): ?>
                    <div class="alert alert-warning">The .env file exists but the database connection failed. Update the credentials below.</div>
                <?php endif; ?>
                <form method="POST">
                    <input type="hidden" name="action" value="save_env">
                    <div class="mb-3">
                        <label class="form-label">Database Host</label>
                        <input type="text" name="db_host" class="form-control" value="<?= htmlspecialchars($env_vars['DB_HOST'] ?? 'localhost') ?>" required>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Database Name</label>
                        <input type="text" name="db_name" class="form-control" value="<?= htmlspecialchars($env_vars['DB_NAME'] ?? 'mtaita_tech_db') ?>" required>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Database User</label>
                        <input type="text" name="db_user" class="form-control" value="<?= htmlspecialchars($env_vars['DB_USER'] ?? '') ?>" required>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Database Password</label>
                        <input type="password" name="db_pass" class="form-control" value="<?= htmlspecialchars($env_vars['DB_PASS'] ?? '') ?>">
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Admin Email</label>
                        <input type="email" name="admin_email" class="form-control" value="<?= htmlspecialchars($env_vars['ADMIN_EMAIL'] ?? 'mtaitajohnson7@gmail.com') ?>" required>
                    </div>
                    <button type="submit" class="btn btn-primary w-100">Save Configuration</button>
                </form>
            </div>
        </div>

        <div class="text-center mt-4">
            <a href="admin/login" class="btn btn-outline-primary">Go to Admin Login</a>
            <a href="/" class="btn btn-outline-secondary">Back to Home</a>
        </div>
    </div>
</body>
</html>
